return {

	Trove = require(script:WaitForChild("Trove")),
	Promise = require(script:WaitForChild("Promise")),
	Spring = require(script:WaitForChild("Spring")),
	Signal = require(script:WaitForChild("Signal")),
	Imagine = require(script:WaitForChild("Imagine")),
	Pool = require(script:WaitForChild("Pool")),
	IllusionIAS = require(script:WaitForChild("IllusionIAS")),

	ExtendedLibraries = require(script:WaitForChild("ExtendedLibraries")),
	DebugUtils = require(script:WaitForChild("DebugUtils")),

	SFXHandler = require(script:WaitForChild("SFXHandler")),
	CameraShaker = require(script:WaitForChild("CameraShaker")),
	Ragdoll = require(script:WaitForChild("Ragdoll")),
	Observer = require(script:WaitForChild("Observer")),
	ActionBuffer = require(script:WaitForChild("ActionBuffer")),
	StateMachine = require(script:WaitForChild("StateMachine")),
	SpectateService = require(script:WaitForChild("SpectateService")),
	LODManager = require(script:WaitForChild("LODManager")),
	Bezier = require(script:WaitForChild("Bezier")),
	DecalProjector = require(script:WaitForChild("DecalProjector")),
	FlashController = require(script:WaitForChild("FlashController")),
	ViewCheck = require(script:WaitForChild("ViewCheck")),

	ConnectToTag = require(script:WaitForChild("ConnectToTag")),
	ConnectToAdded = require(script:WaitForChild("ConnectToAdded")),

	TimeFormatter = require(script:WaitForChild("TimeFormatter")),
	
}